sudo: required

language: go

services:
  - docker

script:
- echo "Here we go!"
- docker build --target=builder -t aws-nuke --no-cache .
- >
  docker run
  --name aws-nuke
  --entrypoint "sh"
  -e CGO_ENABLED=0
  --workdir "/src"
  aws-nuke
  -euxc "make xc && mkdir releases && mv dist/aws-nuke-* releases"
- docker cp -L aws-nuke:/src/releases ./releases
- ls -l *

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: releases/*
  skip_cleanup: true
  on:
    repo: rebuy-de/aws-nuke
    tags: true
