---
regions:
- "eu-west-1"

account-blacklist:
- 1234567890

resource-types:
  targets:
  - DynamoDBTable
  - S3Bucket
  - S3Object
  excludes:
  - IAMRole

accounts:
  555133742:
    presets:
    - "terraform"
    resource-types:
      targets:
      - S3Bucket
    filters:
      IAMRole:
      - "uber.admin"
      IAMRolePolicyAttachment:
      - "uber.admin -> AdministratorAccess"

presets:
  terraform:
    filters:
      S3Bucket:
      - type: glob
        value: "my-statebucket-*"
