name: Golang CI

on:
  push:
    branches: [oreilly-main]
  pull_request:
    types: [opened, reopened, synchronize]
  schedule:
  - cron: '15 3 * * 0'
  workflow_dispatch:

jobs:
  build:
    name: CI Build
    runs-on: ubuntu-22.04
    steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Setup tools
      run: |
        go install golang.org/x/lint/golint@latest
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Check Formatting
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "### Go formatting is off, please execute 'gofmt -w -s .' - see following diff: ###"
          gofmt -s -d .
          exit 1
        fi
    - name: Test Project
      run: |
        make test
    - name: Build Project
      run: |
        make